### ISSUE TITLE
java.lang.NullPointerException: Unexpected error (1.9.4)(Ender staff on the hand shield)

### ISSUE THREAD

**Issue by Lightone** [yyon/grapplemod#24]
when you do a click with the ender staff on the hand of shield the game crash

Error log

`---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 19/07/16 11:56 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.yyon.grapplinghook.ClientProxyClass.launchplayer(ClientProxyClass.java:236)
	at com.yyon.grapplinghook.items.launcherItem.dorightclick(launcherItem.java:61)
	at com.yyon.grapplinghook.items.launcherItem.func_77659_a(launcherItem.java:75)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:160)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:485)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1543)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1748)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.yyon.grapplinghook.ClientProxyClass.launchplayer(ClientProxyClass.java:236)
	at com.yyon.grapplinghook.items.launcherItem.dorightclick(launcherItem.java:61)
	at com.yyon.grapplinghook.items.launcherItem.func_77659_a(launcherItem.java:75)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:160)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:485)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1543)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guartinajo'/12, l='MpServer', x=-650,36, y=68,00, z=-289,38]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-893,65,-897), Chunk: (at 3,4,15 in -56,-57; contains blocks -896,0,-912 to -881,255,-897), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 32370359 game time, 807 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityBat['Bat'/64, l='MpServer', x=-599,50, y=62,80, z=-305,63], EntityBat['Bat'/65, l='MpServer', x=-596,25, y=63,60, z=-306,75], EntityBat['Bat'/66, l='MpServer', x=-596,27, y=63,60, z=-306,45], EntityBat['Bat'/67, l='MpServer', x=-597,65, y=63,05, z=-306,48], EntityBat['Bat'/68, l='MpServer', x=-600,30, y=62,47, z=-305,65], EntityBat['Bat'/69, l='MpServer', x=-597,55, y=62,52, z=-306,64], EntityBat['Bat'/70, l='MpServer', x=-600,62, y=63,21, z=-305,22], EntityBat['Bat'/71, l='MpServer', x=-600,44, y=62,80, z=-305,29], EntityBat['Bat'/72, l='MpServer', x=-600,62, y=62,98, z=-307,92], EntityPlayerSP['Guartinajo'/12, l='MpServer', x=-650,36, y=68,00, z=-289,38], EntitySheep['Sheep'/14, l='MpServer', x=-689,26, y=75,00, z=-279,51], EntitySquid['Squid'/34, l='MpServer', x=-608,17, y=59,00, z=-336,30], EntitySquid['Squid'/35, l='MpServer', x=-633,82, y=61,02, z=-308,98], EntitySquid['Squid'/36, l='MpServer', x=-627,17, y=62,35, z=-316,29], EntityPig['Pig'/38, l='MpServer', x=-625,22, y=74,00, z=-255,49], EntitySheep['Sheep'/39, l='MpServer', x=-667,55, y=77,00, z=-211,26], EntitySquid['Squid'/45, l='MpServer', x=-596,41, y=56,58, z=-332,99], EntitySquid['Squid'/46, l='MpServer', x=-600,40, y=59,53, z=-324,40], EntitySquid['Squid'/47, l='MpServer', x=-597,09, y=59,88, z=-332,67], EntitySquid['Squid'/48, l='MpServer', x=-602,15, y=59,19, z=-337,80], EntitySquid['Squid'/49, l='MpServer', x=-604,40, y=58,99, z=-330,33], EntitySquid['Squid'/50, l='MpServer', x=-605,53, y=59,95, z=-328,10], EntitySquid['Squid'/51, l='MpServer', x=-588,70, y=60,52, z=-344,48], EntitySquid['Squid'/52, l='MpServer', x=-588,58, y=60,64, z=-346,89], EntitySquid['Squid'/53, l='MpServer', x=-587,84, y=60,57, z=-343,56], EntitySquid['Squid'/55, l='MpServer', x=-592,04, y=61,22, z=-349,77], EntityBat['Bat'/57, l='MpServer', x=-606,27, y=62,59, z=-307,53], EntityBat['Bat'/58, l='MpServer', x=-597,20, y=63,27, z=-306,43], EntityBat['Bat'/59, l='MpServer', x=-598,02, y=63,33, z=-306,42], EntityBat['Bat'/60, l='MpServer', x=-601,70, y=63,21, z=-305,00], EntityBat['Bat'/61, l='MpServer', x=-597,47, y=63,60, z=-306,25], EntityBat['Bat'/62, l='MpServer', x=-596,35, y=63,50, z=-306,51], EntityBat['Bat'/63, l='MpServer', x=-600,39, y=63,01, z=-307,66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:490)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 571112384 bytes (544 MB) / 1020067840 bytes (972 MB) up to 1531772928 bytes (1460 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024M -Xmx1512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.28 Powered by Forge 12.17.0.1976 Optifine OptiFine_1.9.4_HD_U_B6 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJAAAA	Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJAAAA	excore{1.5.3} [EXCore] (Excore-1.5.3-1.9.4.jar) 
	UCHIJAAAA	JEI{3.6.8.225} [Just Enough Items] (jei_1.9.4-3.6.8.225.jar) 
	UCHIJAAAA	FEI{1.0.13} [Forever Enough Items] (ForeverEnoughItems-1.0.13-1.9.4.jar) 
	UCHIJAAAA	grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.9.4-v7.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.9.4-forge1.9.4-12.17.0.1976
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@5b766a7e`

**Comment by yyon** [comment]
Fixed in version 8
