### ISSUE TITLE
[1.10.2] - V8 - Server console error

### ISSUE THREAD

**Issue by tristongilley** [yyon/grapplemod#29]
When using the Grappling Hook, I see this error message happen in the console. It doesn't crash the server and the hook performs like it should. Just figured I should report it.

My Forge version is: 1.10.2-12.18.2.2114

I have about 40 mods running alongside this, but I still get this error without them.

```
[18:09:26] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: firstGoodX
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: firstGoodX
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:149) ~[forge-1.10.2-12.18.2.2114-universal.jar:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:98) ~[ObfuscationReflectionHelper.class:?]
	at com.yyon.grapplinghook.network.PlayerMovementMessage$Handler$runner.run(PlayerMovementMessage.java:108) ~[PlayerMovementMessage$Handler$runner.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: firstGoodX
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:96) ~[forge-1.10.2-12.18.2.2114-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:145) ~[forge-1.10.2-12.18.2.2114-universal.jar:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:98) ~[ObfuscationReflectionHelper.class:?]
	at com.yyon.grapplinghook.network.PlayerMovementMessage$Handler$runner.run(PlayerMovementMessage.java:108) ~[PlayerMovementMessage$Handler$runner.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
Caused by: java.lang.NoSuchFieldException: firstGoodX
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_111]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:87) ~[forge-1.10.2-12.18.2.2114-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:145) ~[forge-1.10.2-12.18.2.2114-universal.jar:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:98) ~[ObfuscationReflectionHelper.class:?]
	at com.yyon.grapplinghook.network.PlayerMovementMessage$Handler$runner.run(PlayerMovementMessage.java:108) ~[PlayerMovementMessage$Handler$runner.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

**Comment by GodsVictory** [comment]
same issue for me:

https://gist.github.com/GodsVictory/2f9c20d8d3170fff3a41065197000227

**Comment by Saereth** [comment]
When we get this issue the server lags hard for a couple seconds, disconnects people somtimes before it starts responding again

**Comment by Saereth** [comment]
Any update on this? with a bunch of people on a server it can become unplayable and cause timeouts if people are spam using them.

**Comment by yyon** [comment]
Can you try this and see if it causes any errors?

[https://drive.google.com/file/d/0Bwum1DVR9SNNeTF1cmJGTndHOVk/view?usp=sharing](https://drive.google.com/file/d/0Bwum1DVR9SNNeTF1cmJGTndHOVk/view?usp=sharing)

**Comment by Saereth** [comment]
We have been using this for this evening with about 20 people on our server and no issue so far.

**Comment by yyon** [comment]
1.18 version doesn't use reflection so it fixes this issue
