### ISSUE TITLE
[1.12] it seems like one of the items is not being registered the right way?

### ISSUE THREAD

**Issue by PrinceOfAmber** [yyon/grapplemod#35]
[12:23:04] [main/INFO]: [com.yyon.grapplinghook.grapplemod:registerItems:209]: com.yyon.grapplinghook.items.grappleBow@52abd35
[12:23:04] [main/WARN]: ****************************************
[12:23:04] [main/WARN]: * Registry Item: The object com.yyon.grapplinghook.items.magnetBow@d628eff has been registered twice for the same name grapplemod:magnetbow.
[12:23:04] [main/WARN]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:280)
[12:23:04] [main/WARN]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:261)
[12:23:04] [main/WARN]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:105)
[12:23:04] [main/WARN]: *  at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:146)
[12:23:04] [main/WARN]: *  at com.yyon.grapplinghook.grapplemod.registerItems(grapplemod.java:210)
[12:23:04] [main/WARN]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_grapplemod_registerItems_Register.invoke(.dynamic)...
[12:23:04] [main/WARN]: ****************************************

**Comment by BrisingrAerowing** [comment]
The magnetBow item (Magnetic Grappling Hook) is listed twice for some reason.

[Relevant Line](https://github.com/yyon/grapplemod/blob/1.12/main/java/com/yyon/grapplinghook/grapplemod.java#L210)
