### ISSUE TITLE
Item Entities disappearing?

### ISSUE THREAD

**Issue by TernaryC** [yyon/grapplemod#61]
I've encountered an odd issue while running my server. The following chain of errors outputted to my console:

```
31.03 20:42:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
31.03 20:42:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
31.03 20:42:31 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
31.03 20:42:31 [Server] INFO ... 5 more
31.03 20:42:31 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:42:31 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:05 [Server] Server thread/WARN BunniSloooth moved wrongly!
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:44:23 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:11 [Server] Server thread/WARN Skipping Entity with id realdrops:item_loot
31.03 20:46:15 [Server] Server thread/INFO [STDOUT]: [com.yyon.grapplinghook.controllers.SegmentHandler:updatesegment:278]: Warning: number recursions exceeded
```

These errors are accompanied by the removal of all item entities on the server. Blocks no longer drop items and items dropped by players are deleted. I have yet to find a way to solve this: the world simply no longer spawns item entities.

There is one other mod outputting an error in that chain (Realistic Item Drops by Funwayguy), and I expect that to be the cause, but I wanted to contact you about this issue, as well, since your mod seems to also be sending output during this event.

**Comment by TernaryC** [comment]
The problem has been solved by another moderator on the server. Somehow the gamerule doTileDrops was set to false on our server, despite none of the operators issuing that command and there being no log of it in the server. We can't figure out how it happened, but at least we fixed it.
